#!/bin/ash

# Add script function
source /root/.script_base/base

# Add pack
PACK_DEFAULT="  vim openrc htop curl git zip unzip openssh \
                ca-certificates openssl dpkg-dev dpkg ssmtp xvfb dbus
            "

# update system
update_sys

# install pakage
install_pack

# clean system
clean

# Add Repos php7.0 and php7.1
#RUN wget -O /etc/apk/keys/php-alpine.rsa.pub http://php.codecasts.rocks/php-alpine.rsa.pub && \
#    echo "http://php.codecasts.rocks/7.0" >> /etc/apk/repositories && \
#    echo "http://php.codecasts.rocks/7.1" >> /etc/apk/repositories
