#!/bin/ash

# Add script function
source /root/.script_base/base

# time zone docker
TIME=${TIMEZONE}

#echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
#echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories

# Add pack
PACK_DEFAULT="  vim openrc htop curl git zip unzip openssh autoconf \
                ca-certificates openssl dpkg-dev dpkg ssmtp xvfb dbus tzdata
            "

# update system
update_sys

# install pakage
install_pack

# Setting timezone
echo $TIME
cp /usr/share/zoneinfo/$TIME /etc/localtime
echo "$TIME" > /etc/timezone


# clean system
clean

# Add Repos php7.0 and php7.1
#RUN wget -O /etc/apk/keys/php-alpine.rsa.pub http://php.codecasts.rocks/php-alpine.rsa.pub && \
#    echo "http://php.codecasts.rocks/7.0" >> /etc/apk/repositories && \
#    echo "http://php.codecasts.rocks/7.1" >> /etc/apk/repositories
